# Generated by Django 6.0.2 on 2026-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rir',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='riritem',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
