# Generated by Django 6.0.2 on 2026-03-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rir_hashed_riritem_hashed'),
        ('costum', '0003_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riritem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costum.subcategory'),
        ),
    ]
